[windows_local]
win1 ansible_host=192.168.10.5

[windows_local:vars]
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
ansible_user=.\Administrador
ansible_password=Mrk87dwp_
ansible_winrm_operation_timeout_sec=120
ansible_winrm_read_timeout_sec=180

[windows_domain]
win1 ansible_host=192.168.10.5

[windows_domain:vars]
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
ansible_user=MARQCORD\Administrador
ansible_password=Mrk87dwp_
ansible_winrm_operation_timeout_sec=120
ansible_winrm_read_timeout_sec=180
