[ubuntu_router_master]
uburomas ansible_host=172.17.25.61 ansible_user=uburo ansible_become=true ansible_python_interpreter=/usr/bin/python3 ansible_connection=ssh

[ubuntu_router_backup]
uburoba ansible_host=172.17.25.62 ansible_user=uburoba ansible_become=true ansible_python_interpreter=/usr/bin/python3 ansible_connection=ssh

[ubuntu_dns_secondary]
dns2 ansible_host=192.168.10.6 ansible_user=ubudns ansible_become=true ansible_become_password=mrk87dwp ansible_python_interpreter=/usr/bin/python3 ansible_connection=ssh

[ubuntu_file_server]
fileserver1 ansible_host=192.168.10.7 ansible_user=ubufs ansible_become=true ansible_become_password=mrk87dwp ansible_python_interpreter=/usr/bin/python3 ansible_connection=ssh

[ubuntu_mail]
mail1 ansible_host=192.168.10.9 ansible_user=ubumail ansible_become=true ansible_become_password=mrk87dwp ansible_python_interpreter=/usr/bin/python3 ansible_connection=ssh

[isp2_creator]
isp2 ansible_host=172.17.25.60

[isp2_creator:vars]
ansible_user=uboisp2
ansible_become=true
ansible_become_password=mrk87dwp
ansible_python_interpreter=/usr/bin/python3