[ubuntu_router_master]
# DEPRECADO - Reemplazado por pfSense
# uburomas ansible_host=172.17.25.90 ansible_user=uburomas ansible_become=true ansible_python_interpreter=/usr/bin/python3 ansible_connection=ssh

[ubuntu_router_backup]
# DEPRECADO - Reemplazado por pfSense
# uburoba ansible_host=172.17.25.42 ansible_user=uburoba ansible_become=true ansible_python_interpreter=/usr/bin/python3 ansible_connection=ssh

[pfsense_router_master]
pfsense-master ansible_host=172.17.25.64 ansible_user=admin ansible_password=pfsense ansible_python_interpreter=/usr/bin/python3

[pfsense_router_master:vars]
ansible_connection=ssh
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o KnownHostsFile=/dev/null'


[pfsense_router_backup]
pfsense-backup ansible_host=172.17.25.65 ansible_connection=local

[ubuntu_dns_secondary]
dns2 ansible_host=192.168.10.6 ansible_user=ubudns2 ansible_become=true ansible_python_interpreter=/usr/bin/python3 ansible_connection=ssh

[ubuntu_file_server]
fileserver1 ansible_host=192.168.10.7 ansible_user=ubufs ansible_become=true  ansible_python_interpreter=/usr/bin/python3 ansible_connection=ssh

[ubuntu_mail]
ubumail ansible_host=192.168.10.9 ansible_user=ubumail ansible_become=true ansible_python_interpreter=/usr/bin/python3 ansible_connection=ssh

[zabbix_server]
zabbix ansible_host=192.168.10.10 ansible_user=ansible ansible_become=true ansible_python_interpreter=/usr/bin/python3 ansible_connection=ssh

[isp2_creator]
isp2 ansible_host=172.17.25.35 ansible_user=isp2 ansible_become=true ansible_python_interpreter=/usr/bin/python3 ansible_connection=ssh