[ubuntu_router]
router1 ansible_host=172.17.25.105 ansible_user=uburo ansible_become=true ansible_python_interpreter=/usr/bin/python3 ansible_connection=ssh

[ubuntu_dns_secondary]
dns2 ansible_host=192.168.10.6 ansible_user=ubudns ansible_become=true ansible_python_interpreter=/usr/bin/python3 ansible_connection=ssh
