---
- name: Resetear contraseña root de MariaDB 10.11
  hosts: "{{ target_hosts | default('ubuntu_mail') }}"
  become: true
  gather_facts: false

  vars:
    new_root_password: "PasswordSeguroMySQL2026!"

  tasks:

    - name: Crear directorio override
      ansible.builtin.file:
        path: /etc/systemd/system/mariadb.service.d
        state: directory
        mode: "0755"

    - name: Crear override recovery
      ansible.builtin.copy:
        dest: /etc/systemd/system/mariadb.service.d/recover.conf
        mode: "0644"
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/sbin/mysqld --skip-grant-tables --skip-networking

    - name: Reiniciar MariaDB en recovery
      ansible.builtin.systemd:
        name: mariadb
        state: restarted
        daemon_reload: true

    - name: Esperar socket
      ansible.builtin.wait_for:
        path: /run/mysqld/mysqld.sock
        timeout: 30

    - name: Ver configuración actual de root
      ansible.builtin.shell: |
        mysql -NBe "
        SELECT User,
               Host,
               JSON_VALUE(Priv,'$.plugin')
        FROM mysql.global_priv
        WHERE User='root';
        "
      register: root_info
      changed_when: false

    - debug:
        var: root_info.stdout_lines

    - name: Cambiar plugin y contraseña
      ansible.builtin.shell: |
        mysql <<EOF
        FLUSH PRIVILEGES;

        ALTER USER 'root'@'localhost'
        IDENTIFIED VIA mysql_native_password
        USING PASSWORD('{{ new_root_password }}');

        FLUSH PRIVILEGES;
        EOF
      register: alter_user
      changed_when: true

    - debug:
        var: alter_user.stdout_lines

    - name: Eliminar override
      ansible.builtin.file:
        path: /etc/systemd/system/mariadb.service.d/recover.conf
        state: absent

    - name: Reiniciar MariaDB normal
      ansible.builtin.systemd:
        name: mariadb
        state: restarted
        daemon_reload: true

    - name: Esperar socket
      ansible.builtin.wait_for:
        path: /run/mysqld/mysqld.sock
        timeout: 30

    - name: Verificar login con contraseña
      ansible.builtin.shell: |
        mysql \
          -uroot \
          -p'{{ new_root_password }}' \
          -e "SELECT VERSION();"
      register: verify_password
      changed_when: false

    - debug:
        var: verify_password.stdout_lines