---
- name: Crear usuarios y grupos en Active Directory
  hosts: windows_domain
  gather_facts: false

  vars:
    ad_groups:
      - Administracion
      - TI
      - Ventas

    ad_users:
      - name: admin1
        firstname: Admin
        surname: Uno
        password: "Adm1n@Norcom2026"
        group: Administracion
      - name: admin2
        firstname: Admin
        surname: Dos
        password: "Adm2n@Norcom2026"
        group: Administracion
      - name: ti1
        firstname: TI
        surname: Uno
        password: "T1tech@Norcom2026"
        group: TI
      - name: ti2
        firstname: TI
        surname: Dos
        password: "T2tech@Norcom2026"
        group: TI
      - name: ventas1
        firstname: Ventas
        surname: Uno
        password: "V3ntas@Norcom2026"
        group: Ventas
      - name: ventas2
        firstname: Ventas
        surname: Dos
        password: "V4ntas@Norcom2026"
        group: Ventas

  tasks:
    - name: Crear grupos de seguridad por departamento
      microsoft.ad.group:
        name: "{{ item }}"
        scope: global
        category: security
        state: present
      loop: "{{ ad_groups }}"

    - name: Crear usuarios por departamento en AD
      microsoft.ad.user:
        name: "{{ item.name }}"
        firstname: "{{ item.firstname }}"
        surname: "{{ item.surname }}"
        password: "{{ item.password }}"
        update_password: on_create
        enabled: true
        groups:
          add:
            - "{{ item.group }}"
        state: present
      loop: "{{ ad_users }}"
